---
# tasks file for squid

- name: Include OS Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - install

- name: Install Depand On The Package
  yum: name={{ item }} state=present
  with_items: "{{ Depand_Package }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  tags:
    - install

- name: Install Depand On The Package
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ Depand_Package }}"
  when: ansible_os_family == "Debian" and ansible_distribution_version|int >=16
  tags:
    - install 

- name: Copy Source Package To Target Host
  copy: src=PKG/{{ Squid_Source_Package_Name }}.tar.bz2 dest=/usr/local/src/ 
  tags:
    - install

- name: Uncompression Source Package
  raw: cd /usr/local/src && tar -jxf {{ Squid_Source_Package_Name }}.tar.bz2
  tags:
    - install

- name: Configure Source Code for Squid
  raw: cd /usr/local/src/{{ Squid_Source_Package_Name }} && ./configure {{ Squid_Configure_Optional }}
  tags:
    - install

- name: Compile Source Code for Squid
  raw: cd /usr/local/src/{{ Squid_Source_Package_Name }} && make && make install
  tags:
    - install

- name: Create Cache Directory      
  file: path=/cache state=directory owner=nobody mode=755
  tags:
    - install

- name: Copy Squid's Init Scripts
  copy: src=Conf/{{ansible_os_family}}_init.squid dest=/etc/init.d/squid owner=root group=root mode=0755
  tags:
    - install

- name: Copy Squid's Systemd File
  copy: src=Conf/squid.service dest=/lib/systemd/system/squid.service
  tags: 
    - install

- name: Add Squid To The Launch Of Boot
  shell: systemctl enable squid
  tags:
    - install

- name: Copy Squid's Config Files
  template: src=squid.conf.j2 dest=/usr/local/squid/etc/squid.conf owner=root group=root mode=0644
  notify: Restart Squid.Service
  tags:
    - install
    - service

- name: Ensure Squid Service Is Started And Enabled On Boot
  service: name=squid state=started enabled=yes
  tags:
    - install
    - service

- name: Check Squid Port
  shell: lsof -i:{{ Squid_Port[0] }}|grep squid |awk '{print $1}'
  register: Check_Squid_Port_Result
  tags:      
    - install

- name: Print Install Result
  debug: msg="Install Squid Sucess" 
  when: Check_Squid_Port_Result.stdout == 'squid'
  tags:
    - install
