---
# tasks file for smokeping
- name: Install Depand Packages
  yum: name={{ item }} state=present
  with_items: "{{ Depand_Packages }}"

- name: Install spawn-fcgi and supervisor
  yum: name={{ item }} state=present
  with_items: "{{ EPEL_Packages }}"

- name: Unarchive fping Package
  unarchive: src=packages/fping-4.0.tar.gz dest=/usr/local/src/

- name: Install Fping
  shell: cd /usr/local/src/fping-4.0 && ./configure && make && make install 

- name: Create Software Directory
  file: path=/data/ state=directory owner=root group=root mode=0775

- name: Unarchive Smokeping
  unarchive: src=packages/smokeping-2.7.2.tar.gz  dest=/data/

- name: Create Data Directory
  file: path={{ item }} state=directory mode=0755 owner=nobody group=nobody
  with_items: "{{ Data_Directory }}"

- name: Copy Smokeping Config files
  synchronize: src=config/smokeping-config/ dest=/data/smokeping/etc/

- name: Unarchive Nginx
  unarchive: src=packages/nginx-1.12.0.tar.gz dest=/usr/local/src

- name: Install Nginx
  shell: cd /usr/local/src/nginx-1.12.0 && ./configure --prefix=/data/nginx --with-http_ssl_module --with-pcre --with-http_gzip_static_module && make && make install 

- name: Copy Nginx Config Files
  copy: src=config/nginx/nginx.conf dest=/data/nginx/conf/ owner=root group=root mode=0644

- name: Copy Supervisor Config File
  copy: src=config/nginx/supervisord.conf dest=/etc/supervisord.conf owner=root group=root mode=0644
