# tasks file for MariaDB Installation Or Uninstall

- name: Install Depand On The Package
  apt: name={{ item }} state=present
  with_items: "{{ MariaDB_DepandPackage }}"
  when: ansible_os_family == "Debian" and ansible_distribution_version|int >=16
  tags:
    - install
    - db

- name: Create Mysql User 
  user: name={{ item['name'] }} shell={{ item['shell'] }} createhome=no
  with_items: "{{ Mariadb_User }}"
  tags:
    - install
    - db

- name: Copy SourcePackage To Target Host
  copy: src={{ Mariadb_SourcePackage }}.tar.gz dest=/usr/local/src/ 
  tags:
    - install
    - db

- name: Uncompression SourcePackage
  raw: cd /usr/local/src && tar -zxf {{ Mariadb_SourcePackage }}.tar.gz
  tags:
    - install
    - db

- name: Configure for Mariadb
  raw: cd /usr/local/src/{{ Mariadb_SourcePackage }} && cmake {{ Mariadb_Configure_Optional }}
  tags:
    - install
    - db

- name: Compile for Mariadb
  raw: cd /usr/local/src/{{ Mariadb_SourcePackage }} && make && make install
  tags:
    - install
    - db

- name: Copy InitScript
  copy: src=init.mysqld dest=/etc/init.d/mysqld owner=root group=root mode=0755
  tags:
    - install
    - db

- name: Copy Systemd Mariadb.service
  copy: src=mariadb.service dest=/lib/systemd/system/mariadb.service owner=root group=root mode=0644
  tags:
    - install
    - db

- name: Copy Configfile My.cnf
  copy: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=644
  notify:
    Restart_Mariadb.service
  tags:
    - install
    - db

- name: Chown Mariadb Directory Group
  file: path=/usr/local/mysql/ owner=root group={{ item['group'] }} recurse=yes
  with_items: "{{ Mariadb_User }}"
  tags:
    - install
    - db

- name: Chown Mariadb Data Directory User And Group
  file: path=/usr/local/mysql/data owner={{ item['name'] }} group={{ item['group'] }}
  with_items: "{{ Mariadb_User }}"
  tags:
    - install
    - db

- name: Init Mariadb Database
  raw: cd {{ Mariadb_Dir }} && scripts/mysql_install_db --user={{ item['name'] }}
  with_items: "{{ Mariadb_User }}"
  tags:
   - install
   - service 

- name: Ensure Mariadb Service Is Started And Enabled On Boot
  service: name=mysqld state=started enabled=yes
  tags:
    - install
    - db
    - service
   
- name: Check MariaDB Port
  shell: lsof -i:{{ Mariadb_Port }} |grep mysql |awk '{print $1}'|uniq
  register: Check_MariaDB_Port_Result
  tags:      
    - install
    - db

- name: Print Install Result
  debug: msg="Install MariaDB Sucess" 
  when: Check_MariaDB_Port_Result.stdout == 'mysqld'
  tags:
    - install 
    - db

- name: Add Mariadb Environment On Host
  raw:  echo 'PATH=$PATH:{{ Mariadb_Dir}}/bin' >> /etc/profile.d/mariadb.sh && source /etc/profile
  tags:
    - install
    - db

- name: Create Mysql Link To /usr/bin/
  file: src={{Mariadb_Dir}}/bin/{{item}} dest=/usr/bin/{{ item }} state=link owner=root group=root mode=0644
  with_items:
    - "mysql"
    - "mysqldump"
  tags:
    - install
    - db

- name: Copy .my.cnf File With Root Password Credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf mode=0600
  tags:
    - install
    - db

- name: Remove All Anonymous User Accounts 
  mysql_user: name={{ item.0.name }} host={{ item.1 }} state={{ item.0.mysql.state}} login_unix_socket={{Mariadb_socket}}
  with_subelements:
    - "{{ Mariadb_AnonyousUser }}"
    - mysql.hosts
  tags:
    - install
    - db

- name: Managment Mariadb User
  mysql_user: name={{ item.0.name }} password={{ item.0.mysql.password }} host={{ item.1 }} priv={{ item.0.mysql.privs | join('/') }} state={{ item.0.mysql.state}} login_unix_socket={{Mariadb_socket}}
  with_subelements:
    - "{{ Mariadb_PrivUser }}"
    - mysql.hosts
  tags:
    - install
    - db

- name: Drop Test Database
  mysql_db: name=test state=absent login_unix_socket={{Mariadb_socket}}
  tags:
    - install
    - db

- name: Dumps Mysql Database
  mysql_db: name=charlie state=dump target=/tmp/{{ ansible_hostname }}.sql login_unix_socket={{Mariadb_socket}} 
  tags:
    - install
    - db
    - test

- name: Create Charlie DataBase      
  mysql_db: name=charlie state=present login_unix_socket={{Mariadb_socket}}
  tags:
    - install
    - db
    - test

- name: Import mysql.sql To TestDatabase
  mysql_db: name=charlie state=import target=/tmp/{{ansible_hostname }}.sql login_unix_socket={{Mariadb_socket}} 
  tags:
    - install
    - db
    - test
